spring:
   datasource:
    url: jdbc:mysql://localhost:3306/bs
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
server:
  port: 8080
